name: flutter_animations_example
description: A new Flutter project.
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  cloud_firestore: ^4.9.3
  email_validator: ^2.1.17
  equatable: ^2.0.5
  firebase_auth: ^4.10.1
  firebase_core: ^2.17.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.5
  intl: ^0.18.1
  provider: ^6.0.5
  table_calendar: ^3.0.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - lib/assets/redBoat.png
  uses-material-design: true
